openapi: 3.0.1

info:
  title: ocio-dmz-dev-sams
  description: ''
  version: '1.0'

servers:
- url: https://apidev.cdc.gov/oauth

paths:
  "/":
    get:
      summary: SAMS token validation
      description: Check whether or not a given auth token is valid or expired.
      operationId: sams_validate_token
      parameters:
      - name: access_token
        in: query
        description: Auth token given by SAMS.
        required: true
        schema:
          type: string
      responses:
        '200':
          description:
    post:
      summary: SAMS Password Grant Flow
      description: Generate a new SAMS auth token given a SAMS System username and
        password.
      operationId: sams_password
      parameters:
      - name: Content-Type
        in: header
        description: 'grant_type'
        required: true
        schema:
          type: string
          default: application/x-www-form-urlencoded
      requestBody:
        description: ''
        content:
          application/x-www-form-urlencoded:
            schema:
              required:
              - username
              - password
              properties:
                username:
                  type: string
                  description: SAMS System account username.
                password:
                  type: string
                  description: SAMS System account user password.
      responses:
        '200':
          description: Success
  
  "/refresh":
    post:
      summary: SAMS Refresh Token
      description: Generate new auth token from SAMS given a valid refresh token.
      operationId: sams_refresh_token
      parameters:
      - name: Content-Type
        in: header
        description: ''
        required: true
        schema:
          type: string
          default: application/x-www-form-urlencoded
      requestBody:
        description: ''
        content:
          application/x-www-form-urlencoded:
            schema:
              required:
              - refresh_token
              properties:
                refresh_token:
                  type: string
                  description: Refresh token given by SAMS.
      responses:
        '200':
          description: Success

components:
  securitySchemes:
    sams:
      type: oauth2
      description: This API uses OAuth-2 with the password grant flow. 
      flows:
        password:
          tokenUrl: https://apidev.cdc.gov/oauth
          scopes:
            dex:status: dex status
            
security:
   - sams: []